### ISSUE TITLE
Use ETS instead of Agent?

### ISSUE THREAD

**Issue by lpil** [dre1080/gendex#1]
An agent may be a bottleneck. Would it be better to use an ETS table?

**Comment by dre1080** [comment]
I think you may be right about this. I'll delve further into it. 
What is the main difference between the two?
What would an implementation of this look like?

**Comment by lpil** [comment]
With an agent the agent process receives the message in it's inbox, fetches the data from it's internal state, sends a return message with the state, and then awaits the next one.

I believe that with ETS a process owns the table, and other processes can read from it in parallel.

Here's a page on ETS. http://elixir-lang.org/getting-started/mix-otp/ets.html

Additionally the use of `Map` for such a large dataset will be slow before big maps landed in OTP 18, so an ETS table might be faster even without the parallelization.

Certainly worth creating a benchmark to compare performance.

In this script here I do something extremely similar, only looking up number of syllables rather than looking up likely gender. https://github.com/lpil/reevoo-review-haiku-voodoo/blob/master/lib/rrhv/syllables.ex
